### ISSUE TITLE
Code for data loading and training

### ISSUE THREAD

**Issue by dtchang** [learningmatter-mit/geom#1]
Please provide the Python packages that contain the data loading code (shown in the tutorial) and the training / evaluation code for SchNet (assuming it has been installed). I would like to reproduce the training /evaluation using SchNet. Thanks.

**Comment by simonaxelrod** [comment]
@dtchang Thanks for your interest! We will do that in the next little while as we finalize it and work out all the kinks. For now I can email the code to you. Can you email me at saxelrod@mit.edu and I will respond with the code?
