### ISSUE TITLE
Atomization energies

### ISSUE THREAD

**Issue by shenoynikhil** [learningmatter-mit/geom#10]
I wanted to calculate the reference energies of isolated atoms present in the GEOMDrugs dataset since I want my QM methods to model the interaction energy (total energy - sum of reference energies).

I want to use something like this [spice](https://github.com/openmm/spice-dataset/blob/main/downloader/computeAtomEnergies.py) (used by SPICE dataset), but since GEOM uses semi-empirical methods there needs to be a modification in place. 

Currently, I calculated the isolated atom energies as,
```python
symbol = 'Mg' # example Magnesium
charge = 2 # oxidization state
mol = qcel.models.Molecule(
    symbols=[symbol], geometry=[0, 0, 0], molecular_charge=charge,
)
inp = qcel.models.AtomicInput(
     molecule=mol,
     driver="energy",
     model={"method": "GFN2-xTB"},
)
ret = qcng.compute(inp, "xtb")
energy = ret.return_result
```

Is this correct?

**Comment by simonaxelrod** [comment]
Hey Nikhil,

Thanks for checking out our dataset! I'm not familiar with the psi4 syntax, so I can't say if everything is right, but using GFN2-xTB is definitely right. 

Simon
