### ISSUE TITLE
Different numbers of molecules

### ISSUE THREAD

**Issue by bdy9527** [learningmatter-mit/geom#11]
Hi Simon, thanks for sharing this great dataset!

I noticed that in your paper, there are 7,677 molecules in the Tox21 dataset, covering 98% of the MoleculeNet. However, when I process this file [molecule_net.tar.gz](https://dataverse.harvard.edu/file.xhtml?fileId=5858506&version=4.0), I find that there are only 7,567 molecules in the Tox21 dataset.
Here is my testing code:
```python
import os
import json

molecule_net_path = 'molecule_net'
summary_path = os.path.join(molecule_net_path, 'summary.json')
with open(summary_path, 'r') as f:
    summary = json.load(f)

tox21_dic = {key: val for key, val in summary.items() if 'tox21' in val.get('datasets', [])}
print(len(tox21_dic)) # output: 7567
```
Is there something missing or can you check the provided file?

Thanks a lot!

**Comment by simonaxelrod** [comment]
Hey there,
Thanks for your interest in the dataset! It seems like 7,567 is the right number and 7,677 in the paper was wrong. Not sure how that happened :/

Simon
