### ISSUE TITLE
drug data: drugs_crude.msgpack and rdkit_folder/drugs don't match

### ISSUE THREAD

**Issue by limei0307** [learningmatter-mit/geom#12]
Hi,

Thanks for the great work!

I want to match the RDKit `mol` objects in `rdkit_folder/drugs` to the data in `drugs_crude.msgpack`.
But I found that some SMILES (8621 in total) in `drugs_crude.msgpack` don't exist in `rdkit_folder/summary_drugs.json`, e.g. `CCC(O)(c1ccc(OC)cc1)C(CN1CCOCC1)c1ccccc1`.
In addition, for some molecules, although I can find the corresponding `pickle` file in `rdkit_folder/drugs`, but the number of conformers doesn't match.
Could you please provide more details about these files? Thanks.

**Comment by simonaxelrod** [comment]
The first issue could be because some molecules couldn't be turned into RDKit Mol objects. The second issue is... a problem! To be honest, I'm not completely sure about why it's happening. I'd trust the actual conformers instead of the label for number of conformers when they disagree.

**Comment by limei0307** [comment]
Thanks, Simon! Did you use xyz2mol to get the RDkit Mol objects?

**Comment by simonaxelrod** [comment]
No problem! And yes I did
