### ISSUE TITLE
How to align the order of atoms in 'xyz' with the order in SMILES?

### ISSUE THREAD

**Issue by PKUterran** [learningmatter-mit/geom#2]
The writer says the order is produced by CRET, but I can't figure out what CRET is.

**Comment by simonaxelrod** [comment]
@PKUterran thanks for the question! Crest is the software we used to generate the conformers in the dataset. In terms of ordering, I think the best thing to do is load the pickle files with RDKit mols. Each RDKit mol has one conformer, from which you can get the xyz. It also has all the graph information including bond locations, bond types, smiles, etc. I would check out tutorial 2 which explains how to load the pickles. Does this help?

**Comment by PKUterran** [comment]
Thanks.
