### ISSUE TITLE
How to Checksum

### ISSUE THREAD

**Issue by hansen7** [learningmatter-mit/geom#3]
Thanks for the commitment!

I don't manage to ``generate a checksum and confirm that it matches ours`` as described in the **Data updates** in readme, would you mind elaborating it a bit more？

**Comment by simonaxelrod** [comment]
You're welcome! The dataverse README file [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/JNGTDF) should explain how to do it:

To get the MD5 message digest of a file, run md5sum <your_file> on linux, certutil -hashfile <your_file> md5 on Windows, or md5 <your_file> on mac. This may take a few minutes as the files are quite big.

I'll also add information in the repo README that points you to the dataverse README.
