### ISSUE TITLE
Different SMILES in rdkit mols and key?

### ISSUE THREAD

**Issue by HannesStark** [learningmatter-mit/geom#6]
I found that for some molecules such as `C#CCC#CC#CCC`, the SMILES of the rdkit mol (obtained via `Chem.MolToSmiles(mol)`)
is different from the smiles provided in the key of the molecule, e.g.:

key for molecule:  `C#CCC#CC#CCC`
SMILES of rdkit mol: `[C-4].[C-4].[C-4].[C-4].[C-4].[C-4].[H+].[H+].[H+].[H+].[H+].[H][C-3].[H][C-3].[H][C-3]`

Which is different besides the fact that the hydrogens are included.
Did maybe a mistake happen for these molecules where they were all disconnected into their individual atoms?
Something potentially interesting could be that all examples that I found so far have triple bonds.

**Comment by simonaxelrod** [comment]
Yeah this happened with a few molecules (much more in QM9 than in drugs)- you can check out the second tutorial for other examples of reactive molecules and how to find them. You can also visualize the rdkit mol and check that it really does look broken. I think QM9 just has so many weird unstable structures that crest accidentally broke them when trying to make conformers
